config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :apartments do
    get 'map_location'        # Add this and the "do" "end"
  end

  root 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :address1, presence: true
  # validates :address2, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postal_code, presence: true
  validates :country, presence: true
  validates :owner_name, presence: true
  validates :contact_time, presence: true
  validates :phone_number, presence: true

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    @address1 = address1
    @city = city
    @full_address = (@address1 +", "+ @city)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, email: true
  validates :email, uniqueness: true

  has_many :apartments
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
    # add in the pin drop from the show page to make a multiple pin drops for all apartments
    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  @apartments = Apartment.find(params[:id]) #@apartments may also be found using the set_apartment method provided by scaffolding
    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)
    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

# add in the map location method to call on it in the js file : render the json object
  def map_location
    @apartment = Apartment.find(params[:apartment_id])
    @hash = Gmaps4rails.build_markers(@apartment) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
    render json: @hash.to_json
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:latitude, :longitude, :address1, :address2, :city, :postal_code, :state, :country, :owner_name, :contact_time, :phone_number, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment, html: { multipart: true, class: "form-horizontal", role: "form" }) do |f| %>
  <% if @apartment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h4>

      <ul>
      <% @apartment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image%>
    </div>
  <br>
  <br>
  <div class="form-group">
    <%= f.label :latitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address1, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address1, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address2, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address2, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postal_code, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :postal_code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :owner_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :owner_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contact_time, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :contact_time, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :phone_number, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<div class="page-header">
  <%= link_to apartments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @apartment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing apartment</h1>
</div>

<%= render 'form' %>

app/views/apartments/index.html.erb
<div class="page-header">
  <%= link_to new_apartment_path, class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  New Apartment
  <% end %>
  <h1>Listing apartments</h1>
</div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Address1</th>
        <th>Address2</th>
        <th>City</th>
        <th>Postal code</th>
        <th>State</th>
        <th>Country</th>
        <th>Owner name</th>
        <th>Contact time</th>
        <th>Phone number</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @apartments) do |apartment| %>
      <td><%= apartment.latitude %></td>
      <td><%= apartment.longitude %></td>
      <td><%= apartment.address1 %></td>
      <td><%= apartment.address2 %></td>
      <td><%= apartment.city %></td>
      <td><%= apartment.postal_code %></td>
      <td><%= apartment.state %></td>
      <td><%= apartment.country %></td>
      <td><%= apartment.owner_name %></td>
      <td><%= apartment.contact_time %></td>
      <td><%= apartment.phone_number %></td>
      <td><%= image_tag apartment.image.url(:thumb) %></td>
      <td><%= link_to 'Show', apartment %></td>
      <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
      <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>

</div>
<!-- add map to index page to show all locations of apartments, change the id to mapall to have a new map -->
<div id="mapall" >Google Map will appear here...</div>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {},
    internal: {id: 'mapall'}
  },
  function() {
    markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    // take off zoom so all locations are shows within the height and width of the map
    handler.getMap();
  }
);
</script>

app/views/apartments/new.html.erb
<div class="page-header">
  <%= link_to apartments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New apartment</h1>
</div>

<%= render 'form' %>

app/views/apartments/show.html.erb
<div class="page-header">
  <%= link_to apartments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_apartment_path(@apartment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show apartment</h1>
</div>



<dl class="dl-horizontal">
  <dt>Image</dt>
  <dd><%= image_tag @apartment.image.url(:medium) %></dd>

  <dt>Latitude:</dt>
  <dd><%= @apartment.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @apartment.longitude %></dd>

  <dt>Address1:</dt>
  <dd><%= @apartment.address1 %></dd>

  <dt>Address2:</dt>
  <dd><%= @apartment.address2 %></dd>

  <dt>City:</dt>
  <dd><%= @apartment.city %></dd>

  <dt>Postal code:</dt>
  <dd><%= @apartment.postal_code %></dd>

  <dt>State:</dt>
  <dd><%= @apartment.state %></dd>

  <dt>Country:</dt>
  <dd><%= @apartment.country %></dd>

  <dt>Owner name:</dt>
  <dd><%= @apartment.owner_name %></dd>

  <dt>Contact time:</dt>
  <dd><%= @apartment.contact_time %></dd>

  <dt>Phone number:</dt>
  <dd><%= @apartment.phone_number %></dd>

</dl>
<!-- google map appear on this page with the current location and show the  location of the apartment you are looking at -->
<div id="map" data-apartment-id="<%=@apartment.id%>">Google Map will appear here...</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- adding in google maps API -->

  <script src="//maps.google.com/maps/api/js?v=3.25&key=AIzaSyBmBRLSM_LSa5n7zdtOhvCj1mOABU9B6JE" type="text/javascript"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" type="text/javascript"></script>
  <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, url: users_path, html: { multipart: true} do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.file_field :avatar %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @user, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing user</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="page-header">
  <%= link_to new_user_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New User
  <% end %>
  <h1>Listing users</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @users) do |user| %>
            <td><%= image_tag user.avatar.url(:thumb) %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New user</h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <%= link_to users_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_user_path(@user), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show user</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @user.name %></dd>

  <dt>Email:</dt>
  <dd><%= @user.email %></dd>

</dl>